# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e54d5bae112d96cc111db3ead14f64ca2a4e90f72ce7cabea5eb57cfaadcb259d46430dcf269f9a23ad66af65662bddd6c438747fd1196b4643e4a86adfaaa8c

test:
  secret_key_base: 2f1d4c8e6e828163939dc03c1d1d9bc835cfa70473014110777f0f945dd366858c0702b6eb6cbde70282c7273bd1c09b813afaf19680f55a0e2071807fbd06c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
